import PageLayout from '@/components/landing/PageLayout';
import { Shield, Eye, AlertTriangle, FileText } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

export default function AmlPage() {
  const { lang } = useLanguage();
  const isAr = lang === 'ar';

  const highlights = isAr
    ? [
        { icon: Shield, title: 'امتثال SAMA', desc: 'امتثال كامل لإطار AML/CFT الصادر عن SAMA وجميع توصيات FATF المعتمدة في المملكة العربية السعودية.', color: 'text-blue-600 bg-blue-500/10' },
        { icon: Eye, title: 'مراقبة المعاملات', desc: 'فحص آلي فوري لجميع المعاملات في مواجهة قوائم العقوبات وأنماط الشذوذات السلوكية.', color: 'text-purple-600 bg-purple-500/10' },
        { icon: AlertTriangle, title: 'تقارير STR', desc: 'نقدم تقارير المعاملات المشبوهة (STR) إلى SAFIU وفقاً لما يقتضيه القانون. جميع التقارير سرية.', color: 'text-orange-600 bg-orange-500/10' },
        { icon: FileText, title: 'حفظ السجلات', desc: 'تُحتفظ بجميع سجلات المعاملات ووثائق KYC لمدة لا تقل عن 5 سنوات وفقاً للمتطلبات التنظيمية.', color: 'text-emerald-600 bg-emerald-500/10' },
      ]
    : [
        { icon: Shield, title: 'SAMA Compliance', desc: "Fully compliant with SAMA's AML/CFT Framework and all FATF recommendations as adopted in Saudi Arabia.", color: 'text-blue-600 bg-blue-500/10' },
        { icon: Eye, title: 'Transaction Monitoring', desc: 'Real-time automated screening of all transactions against sanctions lists and behavioral anomaly patterns.', color: 'text-purple-600 bg-purple-500/10' },
        { icon: AlertTriangle, title: 'STR Reporting', desc: 'We file Suspicious Transaction Reports (STRs) with SAFIU as required by law. All reports are confidential.', color: 'text-orange-600 bg-orange-500/10' },
        { icon: FileText, title: 'Record Keeping', desc: 'All transaction records and KYC documentation are retained for a minimum of 5 years per regulatory requirements.', color: 'text-emerald-600 bg-emerald-500/10' },
      ];

  const sections = [
    { title: '1. Regulatory Framework', content: 'TeyraPay operates under the AML/CFT Law issued by Royal Decree No. M/20 dated 05/02/1439H, the Implementing Regulations issued by SAMA, and in accordance with FATF Recommendations. Our compliance program is reviewed annually by our Chief Compliance Officer and independent external auditors.' },
    { title: '2. Know Your Customer (KYC) and Know Your Business (KYB)', content: 'All merchants must complete our KYB verification before processing live payments. This includes: verification of commercial registration and trade license, identification of beneficial owners with ≥25% ownership, PEP (Politically Exposed Person) screening, and ongoing due diligence including enhanced due diligence for higher-risk categories. Ongoing monitoring is performed on all merchant accounts, with periodic KYB refresh for active accounts.' },
    { title: '3. Transaction Monitoring', content: "TeyraPay employs automated transaction monitoring across all payment flows to detect:\n• Unusual transaction volumes or frequencies relative to the merchant's stated business profile\n• Transactions from high-risk jurisdictions\n• Structuring patterns (breaking transactions to avoid reporting thresholds)\n• Payments inconsistent with the merchant's stated business category\nAlerts generated by the monitoring system are reviewed by our compliance team within 24 hours." },
    { title: '4. Prohibited Activities', content: 'TeyraPay will not provide services to merchants or individuals involved in:\n• Money laundering, terrorist financing, or proliferation financing\n• Transactions with sanctioned individuals, entities, or countries\n• Processing payments for unlicensed financial services or gambling\n• Shell companies with no legitimate business purpose\nMerchants found to be engaged in these activities will be immediately terminated and reported to relevant authorities.' },
    { title: '5. Reporting Obligations', content: 'TeyraPay is legally required to file Suspicious Transaction Reports (STRs) with the Saudi Arabia Financial Intelligence Unit (SAFIU) when we suspect that funds are the proceeds of criminal activity. We are prohibited by law from disclosing to the subject of an STR that a report has been filed ("tipping off"). We cooperate fully with law enforcement and regulatory requests for information.' },
    { title: '6. Merchant Responsibilities', content: "By using TeyraPay, merchants agree to:\n• Only process transactions arising from their stated, legitimate business activities\n• Promptly notify TeyraPay of any material change in business model or ownership\n• Cooperate with TeyraPay's enhanced due diligence requests\n• Not facilitate transactions on behalf of unlicensed third parties\nBreach of these obligations is grounds for immediate account termination and may be reported to SAFIU." },
  ];

  return (
    <PageLayout>
      <section className="relative bg-[hsl(222,47%,7%)] py-20 overflow-hidden">
        <div className="absolute inset-0 bg-grid opacity-100" />
        <div className="relative z-10 max-w-3xl mx-auto px-6">
          <span className="inline-block bg-primary/10 border border-primary/20 text-primary text-sm font-semibold px-4 py-1.5 rounded-full mb-6">
            {isAr ? 'قانوني · سياسة مكافحة غسل الأموال' : 'Legal · AML Policy'}
          </span>
          <h1 className="font-syne text-4xl md:text-5xl font-extrabold text-white mb-4">
            {isAr ? 'سياسة مكافحة غسل الأموال' : 'Anti-Money Laundering Policy'}
          </h1>
          <p className="text-white/50">
            {isAr ? 'آخر تحديث: 1 مايو 2026' : 'Last updated: May 1, 2026'}
          </p>
        </div>
      </section>

      <section className="py-16 bg-background">
        <div className="max-w-3xl mx-auto px-6 space-y-10">
          <p className="text-muted-foreground leading-relaxed">
            {isAr
              ? 'تلتزم TeyraPay لتقنية المالية بأعلى المعايير في الامتثال لمكافحة غسل الأموال (AML) ومكافحة تمويل الإرهاب (CFT). تصف هذه السياسة التزاماتنا وضوابطنا ومسؤوليات تجارنا ومستخدمينا بموجب القانون السعودي المعمول به والمعايير الدولية.'
              : 'TeyraPay Financial Technology Co. is committed to the highest standards in Anti-Money Laundering (AML) and Counter-Financing of Terrorism (CFT) compliance. This policy describes our obligations, controls, and the responsibilities of our merchants and users under applicable Saudi Arabian law and international standards.'}
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {highlights.map(item => {
              const Icon = item.icon;
              return (
                <div key={item.title} className="bg-card border border-border rounded-2xl p-5">
                  <div className={`w-9 h-9 ${item.color} rounded-xl flex items-center justify-center mb-3`}>
                    <Icon className="w-4 h-4" />
                  </div>
                  <h3 className="font-syne font-bold text-sm text-foreground mb-1">{item.title}</h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">{item.desc}</p>
                </div>
              );
            })}
          </div>

          {sections.map(s => (
            <div key={s.title}>
              <h2 className="font-syne font-bold text-xl text-foreground mb-3">{s.title}</h2>
              <p className="text-muted-foreground leading-relaxed text-sm whitespace-pre-line">{s.content}</p>
            </div>
          ))}

          <div className="bg-primary/5 border border-primary/15 rounded-2xl p-6">
            <h3 className="font-syne font-bold text-foreground mb-2">
              {isAr ? 'تواصل مع فريق الامتثال' : 'Contact our Compliance team'}
            </h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              {isAr ? (
                <>لاستفسارات مكافحة غسل الأموال أو للإبلاغ عن نشاط مشبوه أو لتقديم المستندات المطلوبة، تواصل مع فريق الامتثال على{' '}<span className="text-primary">compliance@teyrapay.com</span>. تعامل جميع المراسلات بسرية تامة.</>
              ) : (
                <>For AML-related inquiries, to report suspicious activity, or to submit required documentation, contact our compliance team at{' '}<span className="text-primary">compliance@teyrapay.com</span>. All communications are treated with strict confidentiality.</>
              )}
            </p>
          </div>
        </div>
      </section>
    </PageLayout>
  );
}
